module.exports = {
  // action types
  ACTION: "ACTION",
  ASYNC_ACTION: "ASYNC_ACTION",

  // action events
  ACTION_TRIGGERED: "ACTION_TRIGGERED",
  UNDO_ACTION: "UNDO_ACTION",
  REDO_ACTION: "REDO_ACTION",

  // store events
  CHANGE_EVENT: 'STATE_CHANGE',
  SET_EVENT:'SET_STATE_INVOKED',
  REDUCE_EVENT: 'REDUCE_INVOKED',
  ACTION_ADDED: "ACTION_ADDED"
};
