module.exports = {
  ACTION: "RESTATE_ACTION",
  HOOK: "RESTATE_HOOK",
  ACTION_TRIGGERED: "ACTION_TRIGGERED",
  HOOK_TRIGGERED: "HOOK_TRIGGERED",

  // events
  CHANGE_EVENT: 'STATE_CHANGE',
  SET_EVENT:'SET_STATE_INVOKED',
  REDUCE_EVENT: 'REDUCE_INVOKED',
  ACTION_ADDED: "ACTION_ADDED"
};
